[project]
name = "personal-agent-integrations"
version = "0.1.0"
description = "Intégrations Notion, Claude Code, et mobile"
requires-python = ">=3.12"
dependencies = [
    "personal-agent-core",
    "notion-client>=2.4.0",
    "websockets>=12.0",
]

[tool.uv.sources]
personal-agent-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"