[project]
name = "personal-agent-core"
version = "0.1.0"
description = "Agents et moteurs mémoire pour l'agent personnel"
requires-python = ">=3.12"
dependencies = [
    "zep-python>=2.0.2",
    "pydantic>=2.6.0",
    "aiohttp>=3.9.0",
    "fastapi>=0.116.1",
    "neo4j>=5.28.1",
    "qdrant-client>=1.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"